//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IconChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IconChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon ic_daria1 {
            get {
                object obj = ResourceManager.GetObject("ic_daria1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_daria2 {
            get {
                object obj = ResourceManager.GetObject("ic_daria2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_daria3 {
            get {
                object obj = ResourceManager.GetObject("ic_daria3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_daria4 {
            get {
                object obj = ResourceManager.GetObject("ic_daria4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_date1 {
            get {
                object obj = ResourceManager.GetObject("ic_date1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_ding1 {
            get {
                object obj = ResourceManager.GetObject("ic_ding1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_ding2 {
            get {
                object obj = ResourceManager.GetObject("ic_ding2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_ding3 {
            get {
                object obj = ResourceManager.GetObject("ic_ding3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_forte1 {
            get {
                object obj = ResourceManager.GetObject("ic_forte1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_forte2 {
            get {
                object obj = ResourceManager.GetObject("ic_forte2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_forte3 {
            get {
                object obj = ResourceManager.GetObject("ic_forte3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_forte4 {
            get {
                object obj = ResourceManager.GetObject("ic_forte4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_hamsa1 {
            get {
                object obj = ResourceManager.GetObject("ic_hamsa1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna1 {
            get {
                object obj = ResourceManager.GetObject("ic_luna1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna2 {
            get {
                object obj = ResourceManager.GetObject("ic_luna2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna3 {
            get {
                object obj = ResourceManager.GetObject("ic_luna3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna4 {
            get {
                object obj = ResourceManager.GetObject("ic_luna4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna5 {
            get {
                object obj = ResourceManager.GetObject("ic_luna5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna6 {
            get {
                object obj = ResourceManager.GetObject("ic_luna6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna7 {
            get {
                object obj = ResourceManager.GetObject("ic_luna7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_luna8 {
            get {
                object obj = ResourceManager.GetObject("ic_luna8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_mordecai1 {
            get {
                object obj = ResourceManager.GetObject("ic_mordecai1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_vampy1 {
            get {
                object obj = ResourceManager.GetObject("ic_vampy1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_vampy2 {
            get {
                object obj = ResourceManager.GetObject("ic_vampy2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_vampy3 {
            get {
                object obj = ResourceManager.GetObject("ic_vampy3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_vampy4 {
            get {
                object obj = ResourceManager.GetObject("ic_vampy4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_vampy5 {
            get {
                object obj = ResourceManager.GetObject("ic_vampy5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ic_vampy6 {
            get {
                object obj = ResourceManager.GetObject("ic_vampy6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_daria1 {
            get {
                object obj = ResourceManager.GetObject("img_daria1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_daria2 {
            get {
                object obj = ResourceManager.GetObject("img_daria2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_daria3 {
            get {
                object obj = ResourceManager.GetObject("img_daria3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_daria4 {
            get {
                object obj = ResourceManager.GetObject("img_daria4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_date1 {
            get {
                object obj = ResourceManager.GetObject("img_date1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_ding1 {
            get {
                object obj = ResourceManager.GetObject("img_ding1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_ding2 {
            get {
                object obj = ResourceManager.GetObject("img_ding2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_ding3 {
            get {
                object obj = ResourceManager.GetObject("img_ding3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_forte1 {
            get {
                object obj = ResourceManager.GetObject("img_forte1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_forte2 {
            get {
                object obj = ResourceManager.GetObject("img_forte2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_forte3 {
            get {
                object obj = ResourceManager.GetObject("img_forte3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_forte4 {
            get {
                object obj = ResourceManager.GetObject("img_forte4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_hamsa1 {
            get {
                object obj = ResourceManager.GetObject("img_hamsa1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna1 {
            get {
                object obj = ResourceManager.GetObject("img_luna1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna2 {
            get {
                object obj = ResourceManager.GetObject("img_luna2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna3 {
            get {
                object obj = ResourceManager.GetObject("img_luna3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna4 {
            get {
                object obj = ResourceManager.GetObject("img_luna4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna5 {
            get {
                object obj = ResourceManager.GetObject("img_luna5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna6 {
            get {
                object obj = ResourceManager.GetObject("img_luna6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna7 {
            get {
                object obj = ResourceManager.GetObject("img_luna7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_luna8 {
            get {
                object obj = ResourceManager.GetObject("img_luna8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_mordecai1 {
            get {
                object obj = ResourceManager.GetObject("img_mordecai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_vampy1 {
            get {
                object obj = ResourceManager.GetObject("img_vampy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_vampy2 {
            get {
                object obj = ResourceManager.GetObject("img_vampy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_vampy3 {
            get {
                object obj = ResourceManager.GetObject("img_vampy3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_vampy4 {
            get {
                object obj = ResourceManager.GetObject("img_vampy4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_vampy5 {
            get {
                object obj = ResourceManager.GetObject("img_vampy5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_vampy6 {
            get {
                object obj = ResourceManager.GetObject("img_vampy6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] roboto {
            get {
                object obj = ResourceManager.GetObject("roboto", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
